// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Wizard.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Box.H>

class MainWindow {
  bool readyForFinish; 
  int currentPage; 
public:
  Fl_Double_Window* create_window();
private:
  Fl_Wizard *wizard;
public:
  Fl_Input *project_name_edit;
  Fl_Input *project_directory_edit;
  Fl_Choice *game_type_choice;
  static Fl_Menu_Item menu_game_type_choice[];
  Fl_Button *nextButton;
  Fl_Button *prevButton;
  static void next_page(Fl_Button*, MainWindow*);
  static void prev_page(Fl_Button*, MainWindow*);
  static void find_project_dir(Fl_Button*, MainWindow*);
  static const char* generateProjectStructure(const char* path, const char* name, bool scene);
};
#endif
