getLightColor(object);
getLightRadius(object);
getLightIntensity(object);
getLightShadowQuality(object);
getLightShadowBias(object);
getLightShadowBlur(object);
getLightSpotAngle(object);
getLightSpotExponent(object);
setLightColor(object, {r, g, b});
setLightRadius(object, radius);
setLightIntensity(object, intensity);
setLightShadowQuality(object, quality);
setLightShadowBias(object, bias);
setLightShadowBlur(object, blur);
setLightSpotAngle(object, spotAngle);
setLightSpotExponent(object, exponent);