// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef CrashHandler_h
#define CrashHandler_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
extern void send_report(Fl_Button*, void*);

class CrashHandlerDlg {
public:
  Fl_Double_Window* create_window();
  Fl_Text_Display *stack_output;
  static void close_crash_handler(Fl_Button* button, void*);
};
#endif
