// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "MainWindow.h"

Fl_Double_Window* MainWindow::create_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(822, 474, "Profile Viewer");
    w = o;
    o->user_data((void*)(this));
    o->end();
  } // Fl_Double_Window* o
  return w;
}
