// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class MainWindow {
public:
  Fl_Double_Window* create_window();
};
#endif
