// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Chart.H>
#include "Table.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>

class MainWindow {
public:
  Fl_Double_Window* create_window();
  RateTable *table;
  Fl_Chart *chart;
  Fl_Chart *time_chart;
};
#endif
