// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "MainWindow.h"
#include <FL/fl_message.H>
#include <string>

Fl_Double_Window* MainWindow::create_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(822, 474, "Profile Viewer");
    w = o;
    o->user_data((void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(0, 6, 825, 471);
      { Fl_Group* o = new Fl_Group(0, 27, 822, 447, "Profile");
        { table = new RateTable(0, 30, 822, 444);
          table->box(FL_NO_BOX);
          table->color(FL_BACKGROUND_COLOR);
          table->selection_color(FL_BACKGROUND_COLOR);
          table->labeltype(FL_NORMAL_LABEL);
          table->labelfont(0);
          table->labelsize(14);
          table->labelcolor(FL_FOREGROUND_COLOR);
          table->align(Fl_Align(FL_ALIGN_CENTER));
          table->when(FL_WHEN_RELEASE);
        } // RateTable* table
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 27, 822, 444, "Graphs");
        o->hide();
        { chart = new Fl_Chart(6, 48, 297, 249, "Percentage");
          chart->box(FL_ENGRAVED_FRAME);
          chart->color(FL_BACKGROUND_COLOR);
          chart->selection_color(FL_BACKGROUND_COLOR);
          chart->labeltype(FL_NORMAL_LABEL);
          chart->labelfont(0);
          chart->labelsize(14);
          chart->labelcolor(FL_FOREGROUND_COLOR);
          chart->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          chart->when(FL_WHEN_RELEASE);
        } // Fl_Chart* chart
        { time_chart = new Fl_Chart(318, 51, 498, 249, "Time");
          time_chart->box(FL_ENGRAVED_FRAME);
          time_chart->color(FL_BACKGROUND_COLOR);
          time_chart->selection_color(FL_BACKGROUND_COLOR);
          time_chart->labeltype(FL_NORMAL_LABEL);
          time_chart->labelfont(0);
          time_chart->labelsize(14);
          time_chart->labelcolor(FL_FOREGROUND_COLOR);
          time_chart->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          time_chart->when(FL_WHEN_RELEASE);
        } // Fl_Chart* time_chart
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
